### ISSUE TITLE
no video output

### ISSUE THREAD

**Issue by zhywanna** [gaochen315/DynamicNeRF#1]
Dear gaochen, thanks for shaing your great job!
I followed your lead and trained around 240k step currently, but i got no video as you mentioned in readme `Every 100k iterations, you should get videos like the following examples`
and the filename is not the same as your's
![image](https://user-images.githubusercontent.com/47680024/149802670-1686ef53-1c02-46f8-b709-b2fa3681611b.png)

**Comment by gaochen315** [comment]
By default, we pre-train the staticNeRF for N_iters iterations and then jointly train everything. You will be able to see the videos every 100k iterations **after** pre-training.

Hope this helps. Please let me know if you have any other questions. Thanks.

**Comment by zhywanna** [comment]
Thank you so much! So I only need to wait.
Another point is that I tried to turn off pretrain option and I got an error around 5K iteration.
![image](https://user-images.githubusercontent.com/47680024/149870227-3a51cc7c-8dde-42ef-86e5-2a7291b43ddd.png)

**Comment by gaochen315** [comment]
There might be a bug in the code. Are you using `config_Balloon2.txt` with `pretrain` set to `False`? I can look into this issue and get back to you.

**Comment by zhywanna** [comment]
Yes. Thanks again and waiting for your reply!

**Comment by zhywanna** [comment]
Hello, I wonder if the bug was fixed? It seems like "ret" has both tensor type items and tuple of tensors in there. And tuple of tensors items can't be dealt as same as tensor.
