### ISSUE TITLE
How long does it usually take to train a model?

### ISSUE THREAD

**Issue by oscarqht** [gaochen315/DynamicNeRF#12]
Hi. I'm following the steps on [Train a model on your sequence](https://github.com/gaochen315/DynamicNeRF#train-a-model-on-your-sequence) and reached step 7, but it is running like forever. It has been over 83k steps in pretraining and it's still on-going:

```
...
Pretraining step: 83398, Loss: 0.0014436094788834453, Time: 0.125885009765625, expname: kids-at-playground
Pretraining step: 83399, Loss: 0.0024164789356291294, Time: 0.12565231323242188, expname: kids-at-playground
Pretraining step: 83400, Loss: 0.0017029627924785018, Time: 0.1292412281036377, expname: kids-at-playground
Pretraining step: 83401, Loss: 0.0016428650123998523, Time: 0.1261436939239502, expname: kids-at-playground
Pretraining step: 83402, Loss: 0.0021417145617306232, Time: 0.12614750862121582, expname: kids-at-playground
```

**Comment by Earendil-of-Gondor** [comment]
I think they use the same number of iterations for both blended model training and static only pretraining. It's specified by N_iters and defaults to 300001 in your case.
