### ISSUE TITLE
TypeError: expected Tensor as element 0 in argument 0, but got tuple

### ISSUE THREAD

**Issue by zhywanna** [gaochen315/DynamicNeRF#2]
Step: 49993, Loss: 0.013911506161093712, Time: 0.13519692420959473, chain_5frames: False, expname: Balloon2_H270_DyNeRF_pretrain
Step: 49994, Loss: 0.012133732438087463, Time: 0.1316220760345459, chain_5frames: False, expname: Balloon2_H270_DyNeRF_pretrain
Step: 49995, Loss: 0.01327237207442522, Time: 0.1362135410308838, chain_5frames: False, expname: Balloon2_H270_DyNeRF_pretrain
Step: 49996, Loss: 0.01176927424967289, Time: 0.12955403327941895, chain_5frames: False, expname: Balloon2_H270_DyNeRF_pretrain
Step: 49997, Loss: 0.012316515669226646, Time: 0.13320422172546387, chain_5frames: False, expname: Balloon2_H270_DyNeRF_pretrain
Step: 49998, Loss: 0.012100623920559883, Time: 0.1324453353881836, chain_5frames: False, expname: Balloon2_H270_DyNeRF_pretrain
Step: 49999, Loss: 0.011780014261603355, Time: 0.13549208641052246, chain_5frames: False, expname: Balloon2_H270_DyNeRF_pretrain
Traceback (most recent call last):
  File "run_nerf.py", line 763, in <module>
    train()
  File "run_nerf.py", line 452, in train
    **render_kwargs_train)
  File "/DynamicNeRF/render_utils.py", line 98, in render
    rays, chunk, **kwargs)
  File "/DynamicNeRF/render_utils.py", line 26, in batchify_rays
    all_ret = {k: torch.cat(all_ret[k], 0) for k in all_ret}
  File "/DynamicNeRF/render_utils.py", line 26, in <dictcomp>
    all_ret = {k: torch.cat(all_ret[k], 0) for k in all_ret}
TypeError: expected Tensor as element 0 in argument 0, but got tuple

**Comment by zhywanna** [comment]
May be I fix this bug. I added a pr which you can look into

**Comment by gaochen315** [comment]
Good catch. Thanks!
