### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by weders** [gaochen315/DynamicNeRF#4]
Hi @gaochen315 ,

Thanks a lot for releasing the code for DynamicNeRF! This is one of the smoothest experiences I had so far when it comes to running a Github repo - great work!

Just one small thing I noticed is that scikit-image seems to be missing in the dependencies. When I run the motion mask generation script, an import error is raised.

**Comment by gaochen315** [comment]
Thanks for your kind words. I am glad to hear the code is easy to use.

I also updated the dependency list. Good catch.
