### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by ernlavr** [gaochen315/DynamicNeRF#7]
Hi all,

Has anyone tried running the code on Windows? Does the framework use any Linux specific libraries? Is there any information regarding the average time necessary to run the forward-pass with the pretrained models?

Best Regards
-E

**Comment by gaochen315** [comment]
I didn't test the code on Windows. But I guess you need to make sure CUDA is working. As for the running time, it takes about 2s to render a 480 × 270 image using V100.

**Comment by ernlavr** [comment]
Would the 2s estimate be for a whole video or a single frame? I'm looking to experiment with this framework for a research project but I'm looking for something that could render a single viewpoint frame in real-time, atleast under 100ms

**Comment by gaochen315** [comment]
It's for a single frame. I am not focusing too much on the runtime. However, there are many great works on making NeRF more efficient. One example is [Instant Neural Graphics Primitives with a Multiresolution Hash Encoding](https://nvlabs.github.io/instant-ngp/).

**Comment by ernlavr** [comment]
@gaochen315 

Thanks for your response and for the link! I had missed that one during my paper-crawl!
